activemp:
  # 名称
  name: activemp
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2019
  # 文件上传路径
  profile: profile/
  # 获取ip地址开关
  addressEnabled: true

spring:
  activemq:
    broker-url: tcp://120.78.73.168:61616
    user: admin
    password: admin
    pool:
      enabled: false #关闭连接池
      max-connections: 50
